#########################################################################
#      Copyright (C) 2020        Sebastian Francisco Colomar Bauza      #
#      SPDX-License-Identifier:  GPL-2.0-only                           #
#########################################################################
configs:
  nginx.conf:
    file: /run/configs/nginx/etc/nginx/nginx.conf
networks:
  my_network:
    driver: overlay
    external: true
secrets:
  default.conf:
    file: /run/secrets/nginx/etc/nginx/conf.d/default.conf
services:
  nginx:
    configs:
    -
      source: nginx.conf
      target: /etc/nginx/nginx.conf
    image: secobau/nginx
    networks:
    - my_network
    ports:
    - 8080:8080
    secrets:
    -
      source: default.conf
      target: /etc/nginx/conf.d/default.conf
version: "3.8"
#########################################################################
